spring.application.name=ExpenseTracker
spring.datasource.url=jdbc:postgresql://localhost:5432/expense1
spring.datasource.username=postgres
spring.datasource.password=augustas
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
